### ISSUE TITLE
Installation with icu4c v61 fails

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#334]
After upgrading `icu4c` to v61 (using homebrew on macOS), trying to install the dev version of pandoc-citeproc with

```
  stack install pandoc-citeproc \
    --flag "pandoc-citeproc:unicode_collation" \
    --extra-lib-dirs=/usr/local/opt/icu4c/lib \
    --extra-include-dirs=/usr/local/opt/icu4c/include 

```

fails with the error message

```
Building all executables for `pandoc-citeproc' once. After a successful build of all of them, only specified executables will be rebuilt.
pandoc-citeproc-0.14.3.1: build (lib + exe)
Preprocessing library for pandoc-citeproc-0.14.3.1..
Building library for pandoc-citeproc-0.14.3.1..
Preprocessing executable 'pandoc-citeproc' for pandoc-citeproc-0.14.3.1..
Building executable 'pandoc-citeproc' for pandoc-citeproc-0.14.3.1..
Linking .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/pandoc-citeproc/pandoc-citeproc ...
Undefined symbols for architecture x86_64:
  "_u_errorName_60", referenced from:
      ___hs_u_errorName in libHStext-icu-0.7.0.1-CVPjvLaqeE0GCt61ATvPAQ.a(text_icu.o)
  "_ucol_strcoll_60", referenced from:
      ___hs_ucol_strcoll in libHStext-icu-0.7.0.1-CVPjvLaqeE0GCt61ATvPAQ.a(text_icu.o)
  "_ucol_close_60", referenced from:
      ___hs_ucol_close in libHStext-icu-0.7.0.1-CVPjvLaqeE0GCt61ATvPAQ.a(text_icu.o)
  "_ucol_open_60", referenced from:
      ___hs_ucol_open in libHStext-icu-0.7.0.1-CVPjvLaqeE0GCt61ATvPAQ.a(text_icu.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building custom Setup.hs for package pandoc-citeproc-0.14.3.1 using:
      /Users/nick/src/pandoc-build/pandoc-citeproc/.stack-work/dist/x86_64-osx/Cabal-2.0.1.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.1.0 build lib:pandoc-citeproc exe:pandoc-citeproc --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

**Comment by njbart** [comment]
Update: icu4c has been upgraded to v62 now. The new version, again installed via homebrew on macOS, fails with the exact same error message, too.

Since I’ll be having to submit a paper soon where this actually matters, i.e., sorting of the references section is wrong without icu4c, a fix would be much appreciated.

**Comment by njbart** [comment]
It turns out that rebuilding text-icu-0.7.0.1 resolves this issue. (For future reference: On the not entirely trivial task of rebuilding see https://stackoverflow.com/questions/37236892/force-stack-to-rebuild-an-installed-package.)
