### ISSUE TITLE
Fails to build in GHC 8.6.5

### ISSUE THREAD

**Issue by tomjaguarpaw** [jgm/pandoc-citeproc#463]
I'm getting the following when trying to build my project where pandoc-citeproc is included as a transitive dependency from Hakyll ~~pandoc-2.7.3~~ [EDIT: when I also depend on pandoc-2.7.3]. Via pandoc-2.9.2.1 it works fine, but something should be done so one doesn't get a build error with this older version.

```
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - pandoc-citeproc-0.16.2 (lib:pandoc-citeproc) (requires build)
 - hakyll-4.12.5.2 (lib) (requires build)
 - h2-0.0.0.0 (exe:site) (requires build)
Starting     pandoc-citeproc-0.16.2 (all, legacy fallback)
Building     pandoc-citeproc-0.16.2 (all, legacy fallback)

Failed to build pandoc-citeproc-0.16.2.
Build log (
/home/tom/.cabal/logs/ghc-8.6.5/pandoc-citeproc-0.16.2-e653b9147b48ccc3120105c33defddb445555a6e6e6b5b3a273dc8873608128b.log
):
[1 of 1] Compiling Main             ( /tmp/cabal-install.-2737/dist-newstyle/tmp/src-2737/pandoc-citeproc-0.16.2/dist/setup/setup.hs,
/tmp/cabal-install.-2737/dist-newstyle/tmp/src-2737/pandoc-citeproc-0.16.2/dist/setup/Main.o )
Linking /tmp/cabal-install.-2737/dist-newstyle/tmp/src-2737/pandoc-citeproc-0.16.2/dist/setup/setup ...
Configuring pandoc-citeproc-0.16.2...
Preprocessing library for pandoc-citeproc-0.16.2..
Building library for pandoc-citeproc-0.16.2..
[ 1 of 22] Compiling Paths_pandoc_citeproc ( dist/build/autogen/Paths_pandoc_citeproc.hs, dist/build/Paths_pandoc_citeproc.o )
[ 2 of 22] Compiling Text.CSL.Compat.Pandoc ( compat/Text/CSL/Compat/Pandoc.hs, dist/build/Text/CSL/Compat/Pandoc.o )
[ 3 of 22] Compiling Text.CSL.Data    ( src/Text/CSL/Data.hs, dist/build/Text/CSL/Data.o )
[ 4 of 22] Compiling Text.CSL.Exception ( src/Text/CSL/Exception.hs, dist/build/Text/CSL/Exception.o )
[ 5 of 22] Compiling Text.CSL.Util    ( src/Text/CSL/Util.hs, dist/build/Text/CSL/Util.o )
[ 6 of 22] Compiling Text.CSL.Style   ( src/Text/CSL/Style.hs, dist/build/Text/CSL/Style.o )

src/Text/CSL/Style.hs:509:36: error:
    • Couldn't match expected type ‘T.Text’ with actual type ‘[Char]’
    • In the first argument of ‘compareUnicode’, namely
        ‘(map toLower a)’
      In the expression: compareUnicode (map toLower a) (map toLower b)
      In an equation for ‘comp’:
          comp a b = compareUnicode (map toLower a) (map toLower b)
    |
509 |         comp a b = compareUnicode (map toLower a) (map toLower b)
    |                                    ^^^^^^^^^^^^^

src/Text/CSL/Style.hs:509:52: error:
    • Couldn't match expected type ‘T.Text’ with actual type ‘[Char]’
    • In the second argument of ‘compareUnicode’, namely
        ‘(map toLower b)’
      In the expression: compareUnicode (map toLower a) (map toLower b)
      In an equation for ‘comp’:
          comp a b = compareUnicode (map toLower a) (map toLower b)
    |
509 |         comp a b = compareUnicode (map toLower a) (map toLower b)
    |                                                    ^^^^^^^^^^^^^
cabal: Failed to build pandoc-citeproc-0.16.2 (which is required by exe:site
from h2-0.0.0.0). See the build log above for details.
```

**Comment by jgm** [comment]
not sure about the error, but pandoc-citeproc is not a transitive dependency of pandoc.

**Comment by tomjaguarpaw** [comment]
Ah yes, it's from Hakyll.

**Comment by jgm** [comment]
pandoc-citeproc definitely builds on GHC 8.6.5.
In fact, we use that version to build the release binaries that we make available in jgm/pandoc.
And you can see at https://github.com/jgm/pandoc-citeproc/actions/runs/233947588 that it builds with versions of GHC all the way back to 8.0.2.

**Comment by jgm** [comment]
The problem is that an old version of pandoc-citeproc is being built, and probably combined with an incompatible version of some other package (pandoc-types?).  You could probably solve the problem by modifying Hakyll or whatever it is you're compiling to depend on a more recent version of pandoc-citeproc.

**Comment by tomjaguarpaw** [comment]
The problem was a missing upper bound on rfc5051, but was fixed a few days ago by [a Hackage revision](https://hackage.haskell.org/package/pandoc-citeproc-0.16.0.2/revisions/).

**Comment by jgm** [comment]
Ah, sorry for not providing the upper bound in the first place.
